export default {
    login: "sroy04560",
    id: 41642444,
    node_id: "MDQ6VXNlcjQxNjQyNDQ0",
    avatar_url: "https://avatars.githubusercontent.com/u/41642444?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sroy04560",
    html_url: "https://github.com/sroy04560",
    followers_url: "https://api.github.com/users/sroy04560/followers",
    following_url: "https://api.github.com/users/sroy04560/following{/other_user}",
    gists_url: "https://api.github.com/users/sroy04560/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sroy04560/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sroy04560/subscriptions",
    organizations_url: "https://api.github.com/users/sroy04560/orgs",
    repos_url: "https://api.github.com/users/sroy04560/repos",
    events_url: "https://api.github.com/users/sroy04560/events{/privacy}",
    received_events_url: "https://api.github.com/users/sroy04560/received_events",
    type: "User",
    site_admin: false,
    name: "Shubham Roy",
    company: null,
    blog: "linkedin.com/in/shubham-roy-0b71a0220",
    location: "IIIT Bhubaneswar",
    email: null,
    hireable: true,
    bio: "Dare To Imagin Beyond AnyOne's Expectation",
    twitter_username: null,
    public_repos: 9,
    public_gists: 0,
    followers: 30,
    following: 0,
    created_at: "2018-07-24T16:06:19Z",
    updated_at: "2022-04-14T22:58:10Z"
}